version: '3'

services:

  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - selenoid
      - my_network
    ports:
      - '3306:3306'

  opencart:
    container_name: opencart
    image: docker.io/bitnami/opencart:3
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=192.168.0.179:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - selenoid
      - my_network


  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - test_vol:/app
    depends_on:
      - mariadb
      - opencart
    networks:
      - selenoid
      - my_network

networks:
  my_network:
  selenoid:


volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
  test_vol:
